title:             DEV JUNGJAWA
email:             hello@jungjawa.com
description:       Gimana kalo liat-liat dulu aja?
author:            Arif Munandar
baseurl:           "/"
url:               "https://jungjawa.github.io"
permalink: pretty

# Social Profiles
twitter_username:  jungjawa
github_username:   jungjawa
instagram_username: jungjawa

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
